source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/main/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls')),

    path('', include('webapp.urls')),

    path('api/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

source/webapp/urls.py
from django.urls import path, include

from webapp.views import IndexView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

source/webapp/models.py
from django.core.validators import MinValueValidator
from django.db import models


STATUS_NEW = 'new'
STATUS_MODERATED = 'moderated'
STATUS_CHOICES = (
    (STATUS_NEW, 'Новая'),
    (STATUS_MODERATED, 'Модерированная')
)
DEFAULT_STATUS = STATUS_NEW


class Quote(models.Model):
    text = models.TextField(max_length=2000, verbose_name='Текст')
    author = models.CharField(max_length=100, verbose_name='Автор цитаты')
    email = models.EmailField(max_length=100, verbose_name='Почта')
    rating = models.IntegerField(verbose_name='Рейтинг', default=0)
    status = models.CharField(max_length=100, verbose_name='Статус', choices=STATUS_CHOICES, default=STATUS_NEW)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    @classmethod
    def get_moderated(cls):
        return cls.objects.filter(status=STATUS_MODERATED)

    def __str__(self):
        return f'{self.author} - {self.text}'

    class Meta:
        verbose_name = 'Цитата'
        verbose_name_plural = 'Цитаты'


class Vote(models.Model):
    quote = models.ForeignKey('webapp.Quote', related_name='voutes', verbose_name='Цитата', on_delete=models.CASCADE)
    session_key = models.CharField(max_length=40, verbose_name='Ключ сессии')
    rating = models.IntegerField(choices=((1, 'up'), (-1, 'down')), verbose_name='Рейтинг')

    def __str__(self):
        return f'{self.quote}: {self.rating}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'
        ordering = ('quote', 'rating')

source/webapp/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from webapp.models import Quote


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'index.html')

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My Site{% endblock %}</title>


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block links %}{% endblock %}
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <ul class="menu">
            <li><a id="home" href="#">Home</a></li>
                {% if request.user.is_authenticated %}
                    {% block menu %}{% endblock %}
                    <li><a id="create" href="#" >Добавить цитату</a></li>
                    <li><a href="{% url 'accounts:detail' request.user.pk %}">
                        Привет, {{ request.user.get_full_name|default:request.user.username }}
                    </a></li>
                {% endif %}
                {% block auth_menu %}
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a></li>
                        <li><a href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Sign Up</a></li>
                    {% endif %}
                {% endblock %}
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:password_reset_email' %}">Reset Password</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% include 'partial/messages.html' %}
        {% block content %}{% endblock %}
    </div>


    <script

    src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    {% block scripts %}
        <script type="application/javascript" src="{% static 'js/main.js' %}"></script>
    {% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="quote-container hidden">

    </div>

    <div class="detail-container hidden">

    </div>

    <div class="form hidden">
        <h1 class="form-title">Создайте цитату!</h1>
        <form method="post">
            {% csrf_token %}
            <label class="form-label">
                Цитата:
                <textarea id="text-input" name="text"></textarea>
            </label>
            <br>
            <label class="form-label">
                Автор:
                <input id="author-input" type="text" name="author">
            </label>
            <br>
            <label class="form-label">
                Почта:
                <input id="email-input" type="email" name="email">
            </label>
            <input id="submit" type="submit" value="Создать">
        </form>
    </div>


    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}